### ISSUE TITLE
404 Page not found when starting docker

### ISSUE THREAD

**Issue by deunitato-d4l** [IQSS/dataverse-docker#56]
I was trying to start up dataverse following the instructions from the readme page, everything went fine but when accessing the end point `dataverse-dev.localhost` , it shows the following page not found. 
Is there a missing startup process that I missed out on?

![image](https://user-images.githubusercontent.com/83936304/130186558-c3be6601-198b-4c1c-a505-c381fbab7723.png)

Steps taken:
1. Ran the following export commands
```
export traefikhost=localhost
export useremail=team@mydataverse.org
```
2. Create network by running command
`sudo docker network create traefik`
3. Start up docker compose for local
`docker-compose -f docker-compose-local.yml up`
4. Tried to access on browser: `dataverse-dev.localhost` & `localhost`

It seems like PGadmin is working fine as I was able to access the endpoint using port `localhost:8086`.. only dataverse shows the error

![image](https://user-images.githubusercontent.com/83936304/130186905-7f7ea734-64b2-4a09-bd25-39df12884a9c.png)

`docker ps`
![image](https://user-images.githubusercontent.com/83936304/130187214-b1b372de-512e-4ea9-8ab7-93c8fc6b09b4.png)

Some docker logs when running docker compose
```
dataverse        | [#|2021-08-20T06:02:13.056+0000|SEVERE|Payara 5.2020.3|org.eclipse.persistence.session./file:/opt/payara/appserver/glassfish/domains/production/applications/ejb-timer-service-app/WEB-INF/classes/___EJB__Timer__App.ejb|_ThreadID=20;_ThreadName=RunLevelControllerThread-1629439272500;_TimeMillis=1629439333056;_LevelValue=1000;|
dataverse        |   Local Exception Stack: 
dataverse        | Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.payara-p1): org.eclipse.persistence.exceptions.DatabaseException
dataverse        | Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: The connection attempt failed.
dataverse        | Error Code: 0
dataverse        | 	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:318)
dataverse        | 	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:150)
dataverse        | 	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
dataverse        | 	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:225)
dataverse        | 	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:809)
dataverse        | 	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:256)
dataverse        | 	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:772)
dataverse        | 	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:222)
dataverse        | 	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:330)
dataverse        | 	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
dataverse        | 	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:331)
dataverse        | 	at com.sun.enterprise.container.common.impl.EntityManagerWrapper._getDelegate(EntityManagerWrapper.java:197)
dataverse        | 	at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createNamedQuery(EntityManagerWrapper.java:517)
dataverse        | 	at org.glassfish.ejb.persistent.timer.TimerBean.findTimersByOwnerAndState(TimerBean.java:209)
dataverse        | 	at org.glassfish.ejb.persistent.timer.TimerBean.findActiveTimersOwnedByThisServer(TimerBean.java:530)
dataverse        | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataverse        | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dataverse        | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataverse        | 	at java.lang.reflect.Method.invoke(Method.java:498)
dataverse        | 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
dataverse        | 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4796)
dataverse        | 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
dataverse        | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
dataverse        | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
dataverse        | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
dataverse        | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
dataverse        | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataverse        | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dataverse        | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataverse        | 	at java.lang.reflect.Method.invoke(Method.java:498)
dataverse        | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
dataverse        | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
dataverse        | 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4768)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4756)
dataverse        | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
dataverse        | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
dataverse        | 	at com.sun.proxy.$Proxy487.findActiveTimersOwnedByThisServer(Unknown Source)
dataverse        | 	at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.restoreEJBTimers(PersistentEJBTimerService.java:370)
dataverse        | 	at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.resetEJBTimers(PersistentEJBTimerService.java:1401)
dataverse        | 	at com.sun.ejb.containers.EJBTimerService.initPersistentTimerService(EJBTimerService.java:436)
dataverse        | 	at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:257)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.initialize(BaseContainer.java:857)
dataverse        | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
dataverse        | 	at org.glassfish.ejb.startup.EjbApplication.initialize(EjbApplication.java:250)
dataverse        | 	at org.glassfish.internal.data.EngineRef.initialize(EngineRef.java:189)
dataverse        | 	at java.lang.Iterable.forEach(Iterable.java:75)
dataverse        | 	at org.glassfish.internal.data.ApplicationInfo.lambda$initialize$0(ApplicationInfo.java:395)
dataverse        | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
dataverse        | 	at org.glassfish.internal.data.ApplicationInfo.initialize(ApplicationInfo.java:395)
dataverse        | 	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:618)
dataverse        | 	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:332)
dataverse        | 	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
dataverse        | 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
dataverse        | 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
dataverse        | 	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
dataverse        | 	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
dataverse        | 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
dataverse        | 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
dataverse        | 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
dataverse        | 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
dataverse        | 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
dataverse        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dataverse        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dataverse        | 	at java.lang.Thread.run(Thread.java:748)
dataverse        | Caused by: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: The connection attempt failed.
dataverse        | 	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:119)
dataverse        | 	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:138)
dataverse        | 	... 64 more
dataverse        | Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a connection. Cause: Connection could not be allocated because: The connection attempt failed.
dataverse        | 	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)
dataverse        | 	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
dataverse        | 	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
dataverse        | 	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
dataverse        | 	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:113)
dataverse        | 	... 65 more
dataverse        | Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: The connection attempt failed.
dataverse        | 	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:103)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:287)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1532)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:957)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:235)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:528)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:386)
dataverse        | 	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:244)
dataverse        | 	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
dataverse        | 	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
dataverse        | 	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
dataverse        | 	... 69 more
dataverse        | Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: The connection attempt failed.
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:937)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1209)
dataverse        | 	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
dataverse        | 	... 79 more
dataverse        | Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: The connection attempt failed.
dataverse        | 	at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:110)
dataverse        | 	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:920)
dataverse        | 	... 81 more
dataverse        | Caused by: javax.resource.spi.ResourceAllocationException: Connection could not be allocated because: The connection attempt failed.
dataverse        | 	at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:131)
dataverse        | 	at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:87)
dataverse        | 	... 82 more
dataverse        | Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
dataverse        | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:297)
dataverse        | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
dataverse        | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
dataverse        | 	at org.postgresql.Driver.makeConnection(Driver.java:459)
dataverse        | 	at org.postgresql.Driver.connect(Driver.java:261)
dataverse        | 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
dataverse        | 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
dataverse        | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:98)
dataverse        | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:83)
dataverse        | 	at org.postgresql.ds.PGConnectionPoolDataSource.getPooledConnection(PGConnectionPoolDataSource.java:58)
dataverse        | 	at org.postgresql.ds.PGPoolingDataSource.getPooledConnection(PGPoolingDataSource.java:381)
dataverse        | 	at org.postgresql.ds.PGPoolingDataSource.getConnection(PGPoolingDataSource.java:326)
dataverse        | 	at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:117)
dataverse        | 	... 83 more
dataverse        | Caused by: java.net.UnknownHostException: postgres
dataverse        | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
dataverse        | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
dataverse        | 	at java.net.Socket.connect(Socket.java:607)
dataverse        | 	at org.postgresql.core.PGStream.<init>(PGStream.java:81)
dataverse        | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:93)
dataverse        | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
dataverse        | 	... 95 more
dataverse        | |#]
dataverse        | 
dataverse        | [#|2021-08-20T06:02:13.069+0000|WARNING|Payara 5.2020.3|javax.enterprise.ejb.container|_ThreadID=20;_ThreadName=RunLevelControllerThread-1629439272500;_TimeMillis=1629439333069;_LevelValue=900;_MessageID=AS-EJB-00056;|
dataverse        |   A system exception occurred during an invocation on EJB TimerBean, method: public java.util.Set org.glassfish.ejb.persistent.timer.TimerBean.findActiveTimersOwnedByThisServer()|#]
dataverse        | 
dataverse        | [#|2021-08-20T06:02:13.070+0000|WARNING|Payara 5.2020.3|javax.enterprise.ejb.container|_ThreadID=20;_ThreadName=RunLevelControllerThread-1629439272500;_TimeMillis=1629439333070;_LevelValue=900;|
dataverse        |   javax.ejb.EJBException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.payara-p1): org.eclipse.persistence.exceptions.DatabaseException
dataverse        | Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: The connection attempt failed.
dataverse        | Error Code: 0
dataverse        | 	at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:723)
dataverse        | 	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:652)
dataverse        | 	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:482)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4562)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2111)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2081)
dataverse        | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
dataverse        | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
dataverse        | 	at com.sun.proxy.$Proxy487.findActiveTimersOwnedByThisServer(Unknown Source)
dataverse        | 	at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.restoreEJBTimers(PersistentEJBTimerService.java:370)
dataverse        | 	at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.resetEJBTimers(PersistentEJBTimerService.java:1401)
dataverse        | 	at com.sun.ejb.containers.EJBTimerService.initPersistentTimerService(EJBTimerService.java:436)
dataverse        | 	at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:257)
dataverse        | 	at com.sun.ejb.containers.BaseContainer.initialize(BaseContainer.java:857)
dataverse        | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
dataverse        | 	at org.glassfish.ejb.startup.EjbApplication.initialize(EjbApplication.java:250)
dataverse        | 	at org.glassfish.internal.data.EngineRef.initialize(EngineRef.java:189)
dataverse        | 	at java.lang.Iterable.forEach(Iterable.java:75)
dataverse        | 	at org.glassfish.internal.data.ApplicationInfo.lambda$initialize$0(ApplicationInfo.java:395)
dataverse        | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
dataverse        | 	at org.glassfish.internal.data.ApplicationInfo.initialize(ApplicationInfo.java:395)
dataverse        | 	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:618)
dataverse        | 	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:332)
dataverse        | 	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
dataverse        | 	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
dataverse        | 	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
dataverse        | 	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
dataverse        | 	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
dataverse        | 	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
dataverse        | 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
dataverse        | 	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
dataverse        | 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
dataverse        | 	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
dataverse        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dataverse        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dataverse        | 	at java.lang.Thread.run(Thread.java:748)
dataverse        | Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.payara-p1): org.eclipse.persistence.exceptions.DatabaseException
```

**Comment by wpavan** [comment]
Dear @deunitato-d4l ,

Good evening.

Did you find the solution for your question?
I have the same problem.

Thanks.

**Comment by deunitato-d4l** [comment]
@wpavan Yep I manage to get it to work. The problem for me was that it was already working but I access the wrong link. Its hosted on `http://dataverse-dev.localhost:8085`

**Comment by 4tikhonov** [comment]
@deunitato-d4l, @wpavan, we can extend the manual to point to port 8085, it seems it's not really clear. The basic idea is to use traefik proxy and get Dataverse running on a domain name.

**Comment by kuhlaid** [comment]
The doc should say something about the localhost Dataverse login using `localhost:8085`. If I use `localhost:8080` (which is what I have my .env file using...
```
COMPOSE_FILE=./docker-compose-local.yml
hostname=locahost:8080
traefikhost=localhost:8080
```
then when visiting localhost:8080, all I get is a `Welcome to nginx!` message.

Thank you @deunitato-d4l for pointing that out!
